services:
  mcp-sse:
    build: .
    ports:
      - "8000:8000"              # endpoint SSE: http://localhost:8000/sse
    environment:
      - PORT=8000
      - ROOT=/workdir_filesystem          # racine vue par le serveur filesystem
    volumes:
      - ./workdir:/workdir_filesystem:rw  # monte TON dossier local